name: Docker Build

on: 
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened]

permissions:
    contents: read

jobs:
    docker-build:
      strategy:
        fail-fast: false
      runs-on: [ubuntu-latest]

      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.2.0

        - name: Build Docker image
          uses: docker/build-push-action@v5.3.0
          with:
            context: .
            cache-from: type=gha
            cache-to: type=gha,mode=max
            pull: true
            push: false