name: Poetry Build

on: 
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened]

permissions:
    contents: read

jobs:
    poetry-build:
      strategy:
        fail-fast: false
      runs-on: [ubuntu-latest]
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11.2"

        - name: Install Poetry
          run: pipx install poetry=="1.7.1"

        - name: Cache
          uses: actions/cache@v4
          with:
            path: ./.venv
            key: venv-${{ hashFiles('poetry.lock') }}

        - name: Install Playsound
          run: scripts/install-playsound.sh 

        - name: Dependencies
          run: poetry install --without dev

        - name: Build EQAlert
          run: poetry build -vvv | grep -vi ignoring

        - name: Store Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: eqalert-bin
            path: |
              dist/eqalert-*.tar.gz
              dist/eqalert-*.whl
            retention-days: 1
      