name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set-up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.2'

    - name: Install Poetry
      run: pipx install poetry=="1.7.1"

    - name: Cache
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Install Playsound
      run: |
          poetry run pip install --upgrade pip
          poetry run pip install --upgrade wheel
          poetry run pip install playsound

    - name: Install Dependencies
      run: poetry install --without dev

    - name: Configure Token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Build and Publish EQAlert
      run: poetry publish --build
