name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set-up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.2'

    - name: Install Poetry
      run: pipx install poetry=="1.7.1"

    - name: Cache
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Install Playsound
      run: scripts/install-playsound.sh 

    - name: Install Dependencies
      run: poetry install --without dev

    - name: Configure Token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Build
      run: poetry build -vvv | grep -vi ignoring

    - name: Publish
      run: poetry publish